GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0MzkyOGYyOGQyMGVhNmRjNGM4MDIiLCJpYXQiOjE2NDk2ODY4MzUsImV4cCI6MTY1MDI5MTYzNX0._eAp-X0Fj_Zx_4AeQYCAzXH1dfhT0apFNeQ-WFxyDA4

###
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0MzkyOGYyOGQyMGVhNmRjNGM4MDIiLCJpYXQiOjE2NDk2ODY4MzUsImV4cCI6MTY1MDI5MTYzNX0._eAp-X0Fj_Zx_4AeQYCAzXH1dfhT0apFNeQ-WFxyDA4

{
    "name": "Mary",
    "about": "girl",
    "avatar": "https://images.unsplash.com/photo-1647815567584-9fd320e4f039?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2340&q=80",
    "email": "maks1111111@yandex.ru",
    "password": "dfknsqdjNS23"
}

###
POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "maks110@yandex.ru",
  "password": "dfknsqdjNS23"
}

###
POST http://localhost:3000/signup
Content-Type: application/json

{
  "email": "maks@woererekewd.com",
  "password": "dfsdknsds"
}

###
GET http://localhost:3000/users/62531f1ec897bd71bf4d5687
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0MzkyOGYyOGQyMGVhNmRjNGM4MDIiLCJpYXQiOjE2NDk2ODY4MzUsImV4cCI6MTY1MDI5MTYzNX0._eAp-X0Fj_Zx_4AeQYCAzXH1dfhT0apFNeQ-WFxyDA4

###
POST http://localhost:3000/cards
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0MzkyOGYyOGQyMGVhNmRjNGM4MDIiLCJpYXQiOjE2NDk2ODY4MzUsImV4cCI6MTY1MDI5MTYzNX0._eAp-X0Fj_Zx_4AeQYCAzXH1dfhT0apFNeQ-WFxyDA4

{
    "name": "Assa",
    "link": "https://images.unsplash.com/photo-1647815567584-9fd320e4f039?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2340&q=80"
}


###
GET http://localhost:3000/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0MzkyOGYyOGQyMGVhNmRjNGM4MDIiLCJpYXQiOjE2NDk2ODY4MzUsImV4cCI6MTY1MDI5MTYzNX0._eAp-X0Fj_Zx_4AeQYCAzXH1dfhT0apFNeQ-WFxyDA4
###
DELETE http://localhost:3000/cards/625445935982e6aa4b1c4294
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0MzkyOGYyOGQyMGVhNmRjNGM4MDIiLCJpYXQiOjE2NDk2ODY4MzUsImV4cCI6MTY1MDI5MTYzNX0._eAp-X0Fj_Zx_4AeQYCAzXH1dfhT0apFNeQ-WFxyDA4

###
DELETE http://localhost:3000/cards/623a1617dc86338f2435333daac/likes

###
PUT http://localhost:3000/cards/623a1617укукdc86338f2435daac/likes

###
PATCH http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0MzkyOGYyOGQyMGVhNmRjNGM4MDIiLCJpYXQiOjE2NDk2ODY4MzUsImV4cCI6MTY1MDI5MTYzNX0._eAp-X0Fj_Zx_4AeQYCAzXH1dfhT0apFNeQ-WFxyDA4

{
    "name": "M",
    "about": "girl"
}

###
PATCH http://localhost:3000/users/me/avatar
Content-Type: application/json

{
    "avatar": {}
}
